# Generated by Django 3.2.6 on 2021-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('crm', models.CharField(max_length=20)),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
    ]
