# Generated by Django 3.2.6 on 2021-08-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_remove_consultas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='valor',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
